#!/bin/bash
sudo apt update
sudo apt install apache2 -y
sudo apt install nfs-* -y
sudo apt-get install nfs-common -y
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-0f13911e46431608c.efs.ap-south-1.amazonaws.com:/ /var/www/html



________________________________________-----------------------------------



#!/bin/bash
sudo apt update
sudo apt install apache2 -y
sudo apt-get install nfs-common -y
sudo echo "this is viknesh" > /var/www/html/index.html
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport

